version: '3.8'

services:
  claude-yolo:
    build: 
      context: ..
      dockerfile: 96-sandbox/Dockerfile
    container_name: claude-code-yolo
    volumes:
      # Mount project directory (parent folder)
      - ../:/project
      # Mount a separate directory for outputs (optional)
      - ../sandbox-output:/output
    environment:
      - NODE_ENV=development
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    # Resource limits for safety
    mem_limit: 4g
    cpus: '2.0'
    # Network isolation options
    networks:
      - claude-net
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: false
    stdin_open: true
    tty: true

networks:
  claude-net:
    driver: bridge
    internal: false  # Set to true for full network isolation